### ISSUE TITLE
nmap模块按照网上的版本卸载重新安装没有解决，python 2.7

### ISSUE THREAD

**Issue by Desred7eam** [7dog7/masscan_to_nmap#10]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "scan.py", line 69, in NmapScan
    nm = nmap.PortScanner()
AttributeError: 'module' object has no attribute 'PortScanner'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "scan.py", line 69, in NmapScan
    nm = nmap.PortScanner()
AttributeError: 'module' object has no attribute 'PortScanner'

**Comment by 7dog7** [comment]
应该是安装错库了吧，python -m pip install python-nmap
